#!/bin/bash

while read host; do
  echo ${host}
  scp $1 pi@${host}:~/summer-2015/robotics/python &
done <hostfile
wait
while read host; do
  echo ${host}
  ssh pi@${host} "cd ~/summer-2015/robotics/python; nohup python -u $1 & " &
done <hostfile
